name: $(Date:MMddyy)$(Rev:.rrrr)

trigger: none

schedules:
- cron: 0 8 * * Mon # mm HH DD MM DW
  displayName: Localization update
  branches:
    include: 
    - Localization
  always: true

stages:
- stage: __default
  jobs:
  - job: Job1
    pool:
      vmImage: windows-latest
    steps:
    - powershell: |
        $week = (Invoke-WebRequest https://whatsprintis.it -Headers @{"Accept"= "application/json"} | ConvertFrom-Json).week
        $sprint = (Invoke-WebRequest https://whatsprintis.it -Headers @{"Accept"= "application/json"} | ConvertFrom-Json).sprint
        Write-Host "##vso[task.setvariable variable=week]$week"
        Write-Host "##vso[task.setvariable variable=sprint]$sprint"
      displayName: "Determine the number of the week in the sprint and sprint number"

    - powershell: |
        git config --global user.email "$(username)@microsoft.com"
        git config --global user.name "$(username)"
        git checkout -b Localization origin/Localization
        git merge origin/master
        git push origin Localization
      displayName: "Sync with master branch"

    - task: OneLocBuild@2
      condition: and(succeeded(), eq(variables['WEEK'], '3'))
      inputs:
        locProj: 'Localize/LocProject.json'
        outDir: '$(Build.ArtifactStagingDirectory)'
        packageSourceAuth: 'patAuth'
        patVariable: '$(OneLocBuildPAT)'
        isCreatePrSelected: true
        repoType: 'gitHub'
        prSourceBranchPrefix: 'Localize'
        gitHubPatVariable: '$(GitHubPAT)'
        isAutoCompletePrSelected: true
      env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    - powershell: |
        node Localize/bump-version.js
      displayName: Bump tasks' and packages' Localize/bump-version.js
      condition: and(succeeded(), eq(variables['WEEK'], '3'), eq(variables['build.reason'], 'Schedule'))

    - powershell: |
        git add -u
        git commit -m 'Bumped versions'
        git push
      displayName: commit and push versions bump
      condition: and(succeeded(), eq(variables['WEEK'], '3'), eq(variables['build.reason'], 'Schedule'))
    
    - powershell: |
        echo '$(github_token)' | gh auth login --with-token

        $prInfo=(gh api -X GET repos/:owner/:repo/pulls -F head=":owner:$(git branch --show-current)" -f state=open -f base=master | ConvertFrom-Json)

        if ($prInfo.html_url.length -ne 0) {
          Write-Host 'A PR from Localization branch to master already exists'
        }

        $buildUrl = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&_a=summary"
        $body="This PR was auto-generated with [the localization pipeline build]($buildUrl)."

        gh pr create --title 'Localization update' --body $body

        # Getting a link to the opened PR
        $prInfo=(gh api -X GET repos/:owner/:repo/pulls -F head=":owner:$(git branch --show-current)" -f state=open -f base=master | ConvertFrom-Json)
        $env:PR_LINK=$prInfo.html_url
      displayName: Open a PR
      condition: and(succeeded(), eq(variables['WEEK'], '3'), eq(variables['build.reason'], 'Schedule'))

    - powershell: |
        $body = '{"text": "Created tasks localization update PR. Someone please approve/merge it. :please-puss-in-boots:"}'
        Invoke-RestMethod -Uri $(slackUri) -Method Post -Body $body -ContentType 'application/json'
      displayName: 'Send Slack notification about PR opened'
      condition: and(succeeded(), eq(variables['WEEK'], '3'), eq(variables['build.reason'], 'Schedule'))

    - powershell: |
        $buildUrl = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&_a=summary"
        $body = '{"text": "Something went wrong while creating tasks localization update PR. Build: ' + $buildUrl + '"}'
        Invoke-RestMethod -Uri $(slackUri) -Method Post -Body $body -ContentType 'application/json'
      displayName: 'Send Slack notification about error'
      condition: and(failed(), eq(variables['WEEK'], '3'), eq(variables['build.reason'], 'Schedule'))

